acadome/users/__init__.py
from flask import Blueprint

users = Blueprint(
    'users',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/users/static',
    url_prefix='/account'
)

from acadome.users import views

acadome/users/views.py
from datetime import datetime, timedelta
from flask import render_template, redirect, request, url_for, flash, abort
from flask_mail import Message
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from itsdangerous.exc import SignatureExpired
from acadome import app, db, mail, bcrypt, um
from acadome.users import users
from acadome.forms.models import SignUpForm, LoginForm, EditAccountForm, RequestResetForm, ResetPasswordForm, DeleteForm

def get_token(email, expires=300):
    s = Serializer(app.config['SECRET_KEY'], expires)
    return s.dumps({'email': email}).decode('utf-8')

def verify_token(token):
    s = Serializer(app.config['SECRET_KEY'])
    try:
        return s.loads(token)['email']
    except SignatureExpired:
        abort(404)

@users.route('/sign_up', methods=['GET', 'POST'])
@um.user_denied
def sign_up():
    form = SignUpForm(request.form)
    if request.method == 'POST' and form.validate():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        db.users.insert_one({
            'name': form.name.data,
            'affiliation': form.affiliation.data,
            'email': form.email.data,
            'password': hashed,
            'created': datetime.utcnow(),
            'role': 'author',
            'articles': [],
            'verified': False,
            'expires': datetime.utcnow() + timedelta(1),
        })
        token = get_token(form.email.data, expires=24*60*60)
        msg = Message(
            'Account Verification',
            sender=app.config['MAIL_USERNAME'],
            recipients=[form.email.data]
        )
        msg.body = f'''
Welcome to AcaDome! We are glad to have you onboard.
The last step in setting up your account is to verify your email address by clicking on the following link.

{url_for('users.verify', token=token, _external=True)}

If you have not signed up with us, please do not click on the above link.
The account associated with this email address will be deleted in 24 hours if not verified.

Yours sincerely,
Team AcaDome'''
        mail.send(msg)
        flash(f'An email has been sent to {form.email.data} with a link to verify your account. The link will be active for 24 hours, after which your account will be deleted if not verified. You cannot login until your account is verified.')
        return url_for('users.login') if form.js.data else redirect(url_for('users.login'))
    return render_template('sign_up.html', title='Sign Up', um=um, form=form)

@users.route('/verify/<token>')
def verify(token):
    email = verify_token(token)
    db.users.update_one({'email': email}, {
        '$set': {'verified': True},
        '$unset': {'expires': ''}
    })
    if um.user:
        um.reset_user()
        um.set_user(db.users.find_one({'email': email}))
    flash('Thank you for verifying your account. You may proceed to login.')
    return redirect(url_for('users.login'))

@users.route('/login', methods=['GET', 'POST'])
@um.user_denied
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        um.set_user(db.users.find_one({'email': form.email.data}))
        return url_for('users.account') if form.js.data else redirect(url_for('users.account'))
    return render_template('login.html', title='Login', um=um, form=form)

@users.route('/')
@um.user_required
@um.redirect('editor', 'editors.home')
@um.redirect('admin', 'admin.home')
def account():
    articles = []
    for id in um.user['articles'][::-1]:
        articles.append(db.queue.find_one({'id': id}) or db.articles.find_one({'id': id}))
    return render_template('account.html', title='Account', articles=articles, um=um)

@users.route('/user_json')
@um.user_required
def user_json():
    return um.user

@users.route('/edit', methods=['GET', 'POST'])
@um.user_required
def edit_account():
    form = EditAccountForm(request.form)
    if request.method == 'POST' and form.validate():
        db.users.update_one({'email': um.user['email']}, {
            '$set': {
                'name': form.name.data,
                'affiliation': form.affiliation.data
            }
        })
        if form.email.data != um.user['email']:
            db.users.update_one({'email': um.user['email']}, {
                '$set': {
                    'email': form.email.data,
                    'verified': False,
                    'expires': datetime.utcnow() + timedelta(1)
                },
                '$push': {'old_emails': um.user['email']}
            })
            token = get_token(form.email.data, expires=24*60*60)
            msg = Message(
                'Account Verification',
                sender=app.config['MAIL_USERNAME'],
                recipients=[form.email.data]
            )
            msg.body = f'''
Your email address has been changed from {um.user['email']} to {form.email.data}. Please verify your new email address by clicking on the following link.

{url_for('users.verify', token=token, _external=True)}

If you have not made this change, please do not click on the above link.
The account associated with this email address will be deleted in 24 hours if not verified.

Yours sincerely,
Team AcaDome'''
            mail.send(msg)
            um.reset_user()
            flash(f'An email has been sent to {form.email.data} with a link to verify your account. The link will be active for 24 hours, after which your account will be deleted if not verified. You cannot login until your account is verified.')
            return url_for('users.login') if form.js.data else redirect(url_for('users.login'))
        um.reset_user()
        um.set_user(db.users.find_one({'email': form.email.data}))
        return url_for('users.account') if form.js.data else redirect(url_for('users.account'))
    return render_template('edit_account.html', title='Edit Account', um=um, form=form)

def reset_link(email):
    token = get_token(email)
    msg = Message(
        'Password Reset',
        sender=app.config['MAIL_USERNAME'],
        recipients=[email]
    )
    msg.body = f'''
To reset your password, click on the following link:

{url_for('users.reset_password', token=token, _external=True)}

Yours sincerely,
Team AcaDome'''
    mail.send(msg)
    flash(f'An email has been sent to {email} with a link to reset your password. The link will expire in 5 minutes.')
    return url_for('users.logout') if form.js.data else redirect(url_for('users.logout'))

@users.route('/reset_password', methods=['GET', 'POST'])
def request_reset():
    if um.user:
        return redirect(reset_link(um.user['email']))
    form = RequestResetForm(request.form)
    if request.method == 'POST' and form.validate():
        return reset_link(form.email.data)
    return render_template('request_reset.html', title='Request password reset', um=um, form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    email = verify_token(token)
    form = ResetPasswordForm(request.form)
    if request.method == 'POST' and form.validate():
        hashed = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        db.users.update_one({'email': email}, {
            '$set': {'password': hashed}
        })
        flash('Your password has been updated. Please login again.')
        return url_for('users.logout') if form.js.data else redirect(url_for('users.logout'))
    return render_template('reset_password.html', title='Reset password', um=um, form=form, token=token)

@users.route('/logout')
@um.user_required
def logout():
    um.reset_user()
    return redirect(url_for('users.login'))

@users.route('/delete', methods=['GET', 'POST'])
@um.user_required
def delete():
    form = DeleteForm(request.form)
    if request.method == 'POST' and form.validate():
        user = db.users.find_one({'email': um.user['email']})
        user['deleted'] = datetime.utcnow()
        db.deleted_users.insert_one(user)
        db.users.delete_one({'email': um.user['email']})
        msg = Message(
            'Account Deletion',
            sender=app.config['MAIL_USERNAME'],
            recipients=[um.user['email']]
        )
        msg.body = f'''
Your account has been deleted.

You can restore your account by emailing us at team.acadome@gmail.com.

Yours sincerely,
Team AcaDome'''
        mail.send(msg)
        um.reset_user()
        flash('Your account has been deleted. You can restore your account anytime by emailing us at team.acadome@gmail.com.')
        return url_for('articles.home') if form.js.data else redirect(url_for('articles.home'))
    return render_template('delete.html', title='Delete account', um=um, form=form)

acadome/users/templates/account.html
{% extends '_base.html' %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('users.static', filename='style.css') }}" type='text/css'>
{% endblock meta %}

{% block content %}
<main class='grid31 hidden'>
  <article>
    <section class='subsection'>
      <p class='publish-btn'>
        <a href="{{ url_for('articles.publish') }}" class='btn'>+ Publish</a>
      </p>
      <h2>Articles</h2><br>
      <div class='status-table'>
        <h3>Title</h3>
        <h3>Status</h3>
        {% for article in articles %}
        <p>{{ article['title'] }}</p>
        <p class="{{ article['status'].lower() }}">{{ article['status'] }}</p>
        {% endfor %}
      </div>
    </section>
    <section class='subsection'>
      <h2>Inbox</h2><br>
      {% if um.user['inbox'] %}
      <div class='inbox-table'>
        <h3>Sender</h3>
        <h3>Message</h3>
        {% for mail in um.user['inbox'][::-1] %}
        <p>{{ mail['sender'] }}</p>
        <p>{{ mail['message'] }}</p>
        {% endfor %}
      </div>
      {% else %}
      <p>No messages.</p>
      {% endif %}
    </section>
  </article>

  <aside>
    <h2>Account</h2><br>
    <dl>
      <dt class='small'>Name</dt>
      <dd>{{ um.user['name'] }}</dd><br>
      {% if um.user['affiliation'] %}
      <dt class='small'>Affiliation</dt>
      <dd>{{ um.user['affiliation'] }}</dd><br>
      {% endif %}
      <dt class='small'>Email address</dt>
      <dd>{{ um.user['email'] }}</dd><br>
    </dl>
    <p>
      <a href="{{ url_for('users.edit_account') }}" class='btn'>Edit</a>
      <a href="{{ url_for('users.delete') }}" class='btn red'>Delete</a><br>
      <a href="{{ url_for('users.request_reset') }}" class='red'>Change password</a>
    </p>
  </aside>
</main>
{% endblock content %}

acadome/users/templates/delete.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('forms.static', filename='main.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('forms.static', filename='router.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('users.delete') }}" method='POST' autocomplete='off' id='delete-form'>
    <h2>Delete account</h2>
    {{ form.csrf_token }}
    <div class='hidden'>
      {{ render_field(form.email) }}
    </div>
    {{ render_field(form.password) }}
    <div class='fields-flex'>
      <span><a href="{{ url_for('users.account') }}" class='red'>Back</a></span>
      <button type='submit' class='btn'>Delete</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}

acadome/users/templates/edit_account.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('forms.static', filename='main.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('forms.static', filename='router.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('users.edit_account') }}" method='POST' autocomplete='off' id='edit-account-form'>
    <h2>Edit Account</h2>
    {{ form.csrf_token }}
    {{ render_field(form.name) }}
    {{ render_field(form.affiliation) }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    <div class='fields-flex'>
      <span><a href="{{ url_for('users.account') }}" class='red'>Back</a></span>
      <button type='submit' class='btn'>Update</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}

acadome/users/templates/login.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('forms.static', filename='main.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('forms.static', filename='router.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('users.login') }}" method='POST' autocomplete='off' id='login-form'>
    <h2>Login</h2>
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    <div class='fields-flex'>
      <span><a href="{{ url_for('users.request_reset') }}" class='red'>Forgot password</a></span>
      <button type='submit' class='btn'>Login</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}

acadome/users/templates/request_reset.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('forms.static', filename='main.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('forms.static', filename='router.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('users.request_reset') }}" method='POST' autocomplete='off' id='request-reset-form'>
    <h2>Request Password Reset</h2>
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    <div class='fields-flex'>
      <span><a href="{{ url_for('users.login') }}" class='red'>Back</a></span>
      <button type='submit' class='btn'>Submit</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}

acadome/users/templates/reset_password.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('forms.static', filename='main.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('forms.static', filename='router.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('users.reset_password', token=token) }}" method='POST' autocomplete='off' id='reset-password-form'>
    <h2>Reset Password</h2>
    {{ form.csrf_token }}
    {{ render_field(form.password) }}
    <div class='fields-flex'>
      <span><a href="{{ url_for('users.login') }}" class='red'>Back</a></span>
      <button type='submit' class='btn'>Submit</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}

acadome/users/templates/reset_password1.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link href="{{ url_for('static', filename='css/forms.css') }}" rel='stylesheet' type='text/css'>
<script defer src="{{ url_for('static', filename='js/forms.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('users.static', filename='main.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('users.reset_password1') }}" method='POST' autocomplete='off' id='reset-password-form-1'>
    <h2>Reset Password</h2>
    {{ form.csrf_token }}
    {{ render_field(form.email) }}
    <div class='fields-flex'>
      <span><a href="{{ url_for('users.login') }}" class='red'>Back</a></span>
      <button type='submit' class='btn'>Submit</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}

acadome/users/templates/reset_password2.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link href="{{ url_for('static', filename='css/forms.css') }}" rel='stylesheet' type='text/css'>
<script defer src="{{ url_for('static', filename='js/forms.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('users.static', filename='main.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('users.reset_password2', token=token) }}" method='POST' autocomplete='off' id='reset-password-form-2'>
    <h2>Reset Password</h2>
    {{ form.csrf_token }}
    {{ render_field(form.password) }}
    <div class='fields-flex'>
      <span><a href="{{ url_for('users.login') }}" class='red'>Back</a></span>
      <button type='submit' class='btn'>Submit</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}

acadome/users/templates/sign_up.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('forms.static', filename='main.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('forms.static', filename='router.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('users.sign_up') }}" method='POST' autocomplete='off' id='sign-up-form'>
    <h2>Sign Up</h2>
    {{ form.csrf_token }}
    {{ render_field(form.name) }}
    {{ render_field(form.affiliation) }}
    {{ render_field(form.email) }}
    {{ render_field(form.password) }}
    <div class='field fields-flex'>
      <div>
        {% if form.ua.errors %}
        {{ form.ua(class='field-error') }}
        {% else %}
        {{ form.ua }}
        {% endif %}
        <label for='agreement' id='agreement'>
          I accept the <a href="{{ url_for('gen.user_agreement') }}" class='link' target='_blank'>user agreement</a>.
        </label>
      </div>
      <button type='submit' class='btn'>Sign Up</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}