acadome/gen/__init__.py
from flask import Blueprint

gen = Blueprint(
    'gen',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/gen/static'
)

from acadome.gen import views

acadome/gen/views.py
from flask import render_template, request, flash
from flask_mail import Message
from acadome import app, um, mail
from acadome.gen import gen
from acadome.forms.models import ContactForm

@gen.route('/about')
def about():
    return render_template('about.html', title='About', um=um)

@gen.route('/workflow')
def workflow():
    return render_template('workflow.html', title='Workflow', um=um)

@gen.route('/financial_model')
def finances():
    return render_template('finances.html', title='Financial model', um=um)

@gen.route('/user_agreement')
def user_agreement():
    return render_template('user_agreement.html', title='User agreement', um=um)

@gen.route('/publishing_agreement')
def publishing_agreement():
    return render_template('publishing_agreement.html', title='Publishing agreement', um=um)

@gen.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm(request.form)
    if request.method == 'POST' and form.validate():
        msg1 = Message(
            'Query',
            sender=app.config['MAIL_USERNAME'],
            recipients=[app.config['MAIL_USERNAME']]
        )
        msg1.body = f'''
Name: {form.name.data}

Email: {form.email.data}

Query: {form.query.data}'''
        mail.send(msg1)
        msg2 = Message(
            'Query Received',
            sender=app.config['MAIL_USERNAME'],
            recipients=[form.email.data]
        )
        msg2.body = '''
We have received your query and will get back to you within two working days.
Thank you for your patience.

Yours sincerely,
Team AcaDome'''
        mail.send(msg2)
        flash('Your query has been submitted successfully.')
        return url_for('articles.home') if form.js.data else redirect(url_for('articles.home'))
    return render_template('contact.html', title='Contact', um=um, form=form)

acadome/gen/templates/about.html
{% extends '_base.html' %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('gen.static', filename='style.css') }}" type='text/css'>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <article>
    <section>
      <h2>About AcaDome</h2>
      <p>We are a self-publishing open access mega-journal.</p>
    </section>

    <section>
      <h2>Our principles</h2>
      <ul class='list'>
        <li>No paywalls. No registration. Absolute <a href='https://www.openaccess.nl/en/what-is-open-access' class='orange' target='_blank'>open access</a>.</li>
        <li>Streamline the <a href="{{ url_for('gen.workflow') }}" class='orange'>editorial workflow</a>.</li>
        <li>Maintain transparent <a href="{{ url_for('gen.finances') }}" class='orange'>pricing</a>.</li>
        <li>Collaborate with academia.</li>
        <li>publisher: self</li>
        <li>scope: digital</li>
        <li>issues: rolling</li>
        <li>issn</li>
      </ul>
    </section>

    <section>
      <h2>Editorial board</h2>
      <p></p>
    </section>

    <section>
      <h2>Advisory board</h2>
      <p></p>
    </section>

    <section>
      <h2>Contact</h2>
      <p>If you have a user account, please login and send us your query. If you do not have a user account, use this <a href="{{ url_for('gen.contact') }}" class='orange'>contact form</a>, or email us directly at <a href='mailto:team.acadome@gmail.com' class='orange'>team.acadome@gmail.com</a>.</p>
    </section>
  </article>
</main>
{% endblock content %}

acadome/gen/templates/contact.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('forms.static', filename='main.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('forms.static', filename='router.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('gen.contact') }}" method='POST' autocomplete='off' id='contact'>
    <h2>Contact</h2>
    {{ form.csrf_token }}
    {{ render_field(form.name) }}
    {{ render_field(form.email) }}
    {{ render_field(form.query) }}
    <div class='fields-flex'>
      <span><a href="{{ url_for('gen.about') }}" class='red'>Back</a></span>
      <button type='submit' class='btn'>Submit</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}

acadome/gen/templates/finances.html
{% extends '_base.html' %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('gen.static', filename='style.css') }}" type='text/css'>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <article>
    <h2>Financial Model</h2>
    <p>The article processing charge (APC) is &#128; 400.</p>
  </article>
</main>
{% endblock content %}

acadome/gen/templates/publishing_agreement.html
{% extends '_base.html' %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('gen.static', filename='style.css') }}" type='text/css'>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <article>
    <h2>Publishing Agreement</h2>
    <ul class='list'>
      <li>The author will retain copyright of the article.</li>
      <li>All articles will be published under the <a href='https://creativecommons.org/licenses/by/4.0/' class='anchor-2' target='_blank'>CC BY license</a>.</li>
      <li>Retraction of an article is subject to the editor's discretion.</li>
    </ul>
  </article>
</main>
{% endblock content %}

acadome/gen/templates/user_agreement.html
{% extends '_base.html' %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('gen.static', filename='style.css') }}" type='text/css'>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <article>
    <h2>User Agreement</h2>
    <ul class='list'>
      <li></li>
    </ul>
  </article>
</main>
{% endblock content %}

acadome/gen/templates/workflow.html
{% extends '_base.html' %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('gen.static', filename='style.css') }}" type='text/css'>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <article>
    <h2>Editorial workflow</h2>
    <p></p>
  </article>
</main>
{% endblock content %}