acadome/articles/__init__.py
from flask import Blueprint

articles = Blueprint(
    'articles',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/articles/static'
)

from acadome.articles import views

acadome/articles/views.py
import os
import random
from datetime import datetime
from flask import render_template, redirect, url_for, request, flash, abort
from werkzeug.utils import secure_filename
from flask_mail import Message
from acadome import app, db, mail, um
from acadome.articles import articles
from acadome.forms.models import PublishForm

@articles.route('/')
def home():
    query = request.args.get('search')
    if query:
        query = query.strip()
        articles = db.articles.find({'$text': {'$search': query}})
        return render_template('search.html', title=query, query=query, articles=articles, um=um)
    return render_template('home.html', um=um)

@articles.route('/fields')
def fields():
    fields_ = db.fields.find().sort([('name', 1)])
    return render_template('fields.html', title='Fields of research', fields=fields_, um=um)

@articles.route('/field/<string:field>')
def field_search(field):
    field = field.replace('_', ' ')
    if not db.fields.find_one({'name': field}):
        abort(404)
    articles = db.articles.find({'field': field}).sort([('year', -1), ('title', 1)])
    return render_template('search.html', title=field, articles=articles, um=um)

@articles.route('/author/<string:author>')
def author_search(author):
    author = author.replace('_', ' ')
    if not db.articles.count_documents({'authors': author}):
        abort(404)
    articles = db.articles.find({'authors': author}).sort([('year', -1), ('title', 1)])
    return render_template('search.html', title=author, query=author, articles=articles, um=um)

@articles.route('/article/<string:id>')
def article(id):
    article = db.articles.find_one({'id': id})
    return render_template('article.html', title=article['title'], article=article, um=um)

def generate_id():
    r = str(random.randint(10000000, 99999999))
    if db.queue.find_one({'id': r}) or db.articles.find_one({'id': r}):
        return generate_id()
    return r

@articles.route('/account/publish', methods=['GET', 'POST'])
@um.user_required
def publish():
    form = PublishForm(request.form)
    if request.method == 'POST' and form.validate():
        id = generate_id()
        if form.authors.data:
            authors = [ca.strip() for ca in form.authors.data.split(',')]
            authors.insert(0, um.user['name'])
        else:
            authors = [um.user['name']]
        keywords = [kw.strip() for kw in form.keywords.data.split(',')]
        reviewers = [rev.strip() for rev in form.reviewers.data.split(',') if rev]
        db.queue.insert_one({
            'id': id,
            'title': form.title.data,
            'authors': authors,
            'submitted': datetime.utcnow(),
            'abstract': form.abstract.data,
            'keywords': keywords,
            'field': form.field.data,
            'reviewers': reviewers,
            'status': 'Submitted',
            'uploader': um.user['email'],
            'votes': {
                'accept': [],
                'reject': []
            }
        })
        db.users.update_one({'email': um.user['email']}, {
            '$push': {'articles': id}
        })
        path = os.path.join(app.root_path + url_for('articles.static', filename='pdfs/queue/'), id)
        os.mkdir(path)
        preprint = request.files['preprint']
        preprint.seek(0)
        preprint.save(os.path.join(path, 'preprint.pdf'))
        images = request.files.getlist('images')
        for image in images:
            filename = secure_filename(image.filename)
            image.seek(0)
            image.save(os.path.join(path, filename))
        msg = Message(
            'Preprint received',
            sender=app.config['MAIL_USERNAME'],
            recipients=[um.user['email']]
        )
        msg.body = '''
We have received your preprint. Thank you for choosing to publish with AcaDome.

Yours sincerely,
Team AcaDome'''
        mail.send(msg)
        flash('Your preprint has been submitted successfully.')
        email = um.user['email']
        um.reset_user()
        um.set_user(db.users.find_one({'email': email}))
        return url_for('users.account') if form.js.data else redirect(url_for('users.account'))
    return render_template('publish.html', title='Publish', um=um, form=form)

acadome/articles/templates/article.html
{% extends '_base.html' %}

{% block content %}
<main class='grid31 hidden'>
  <article>
    <div class='subsection'>
      {% if article['preprint'] %}
      <h2>[Preprint] {{ article['title'] }}</h2>
      {% else %}
      <h2>{{ article['title'] }}</h2>
      {% endif %}
      <p>
        {% for author in article['authors'] %}
        {% if author == author_ %}
        {% if author == article['authors'][-1] %}
        <span>{{ author }}</span>
        {% else %}
        <span>{{ author }}, </span>
        {% endif %}
        {% else %}
        {% if author == article['authors'][-1] %}
        <span><a href="{{ url_for('articles.author_search', author=author.replace(' ', '_')) }}" class='blue'>{{ author }}</a></span>
        {% else %}
        <span><a href="{{ url_for('articles.author_search', author=author.replace(' ', '_')) }}" class='blue'>{{ author }}</a>, </span>
        {% endif %}
        {% endif %}
        {% endfor %}
      </p>
    </div>
    <div class='subsection'>
      {% if article['preprint'] %}
      <a href="{{ url_for('articles.static', filename='pdfs/queue/' + article['id'] + '/preprint.pdf') }}" target='_blank' class='btn'>PDF</a>
      {% else %}
      <a href="{{ url_for('articles.static', filename='pdfs/' + article['id'] + '.pdf') }}" target='_blank' class='btn'>PDF</a>
      {% endif %}
    </div>
    <div class='subsection'>
      <h3>Abstract</h3>
      <p>{{ article['abstract'] }}</p>
    </div>
    <div class='subsection'>
      <h3>Keywords</h3>
      <p>{{ ' | '.join(article['keywords']) }}</p>
    </div>
  </article>
  <aside>
    <div class='subsection'>
      <p>
        Submitted on: {{ article['submitted'].strftime('%d %B %Y') }}<br>
        Accepted on: {{ article['accepted'].strftime('%d %B %Y') }}<br>
        {% if not article['preprint'] %}
        Published on: {{ article['published'].strftime('%d %B %Y') }}
        {% endif %}
      </p>
    </div>
    {% if not article['preprint'] %}
    <div class='subsection'>
      <h3>DOI</h3>
      <p><a href='#' class='blue'>{{ article['doi'] }}</a></p>
    </div>
    {% endif %}
    <div class='subsection'>
      <h3>License</h3>
      <a rel='license' href='http://creativecommons.org/licenses/by/4.0/' target='_blank'>
        <img alt='Creative Commons License' src='https://i.creativecommons.org/l/by/4.0/88x31.png'>
      </a><br>
      <p>
        Published under a <a rel='license' href='http://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International License</a>.
      </p>
    </div>
  </aside>
</main>
{% endblock content %}

acadome/articles/templates/fields.html
{% extends '_base.html' %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('articles.static', filename='style.css') }}" type='text/css'>
{% endblock meta %}

{% block content %}
<main class='categories hidden'>
  <h2>Fields of research</h2>
  <ul class='fields-grid'>
    {% for field in fields %}
    <li><a href="{{ url_for('articles.field_search', field=field['name'].replace(' ', '_')) }}">{{ field['name'] }}</a></li>
    {% endfor %}
  </ul>
</main>
{% endblock content %}

acadome/articles/templates/home.html
{% extends '_base.html' %}

{% block meta %}
<link rel='preload' href="{{ url_for('static', filename='images/logo_400x231.png') }}" as='image'>
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<link rel='stylesheet' href="{{ url_for('articles.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('articles.static', filename='main.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='home hidden'>
  <figure>
    <img src="{{ url_for('static', filename='images/logo_400x231.png') }}" alt='AcaDome logo' id='logo'>
  </figure>

  <form action="{{ url_for('articles.home') }}" method='GET' autocomplete='off' id='search-form'>
    <div class='fields-flex'>
      <input type='search' name='search' placeholder='Search database'>
      <button type='submit' class='btn'>
        <img src="{{ url_for('static', filename='images/search.png') }}" width='16px' height='16px'>
      </button>
    </div>
  </form>

  <p>Or browse through the <a href="{{ url_for('articles.fields') }}" class='orange'>fields of research</a>.</p>
</main>
{% endblock content %}

acadome/articles/templates/publish.html
{% extends '_base.html' %}
{% from '_form_field.html' import render_field %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('forms.static', filename='main.js') }}" type='text/javascript'></script>
<script defer src="{{ url_for('forms.static', filename='router.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='hidden'>
  <form action="{{ url_for('articles.publish') }}" method='POST' enctype='multipart/form-data' autocomplete='off' id='publish-form'>
    {{ form.csrf_token }}
    <h2>Publish with AcaDome</h2>
    <p>Before you send us your preprint, please read the <a href="" class='orange'>guidelines</a>.</p><br>
    {{ render_field(form.title) }}
    {{ render_field(form.authors) }}
    {{ render_field(form.abstract) }}
    {{ render_field(form.keywords) }}
    {{ render_field(form.field) }}
    <div class='field'>
      <label>Upload files</label>
      <div class='fields-flex'>
        <div>
          {{ form.preprint.label(class='btn') }}
          {{ form.preprint(class='hidden') }}
        </div>
        {% if form.preprint.errors %}
        <input type='text' name='preprint-name' class='field-error' disabled>
        {% else %}
        <input type='text' name='preprint-name' disabled>
        {% endif %}
      </div>
      <div class='field-error-desc'>
        <span id='preprint-error' class='small'>{{ form.preprint.errors[0] }}</span><br>
      </div>
    </div>
    <div class='field'>
      <div class='fields-flex'>
        <div>
          {{ form.images.label(class='btn') }}
          {{ form.images(id='images', class='hidden') }}
        </div>
        {% if form.images.errors %}
        <input type='text' name='images-name' class='field-error' disabled>
        {% else %}
        <input type='text' name='images-name' disabled>
        {% endif %}
      </div>
      <div class='field-error-desc'>
        <span id='images-error' class='small'>{{ form.images.errors[0] }}</span><br>
      </div>
    </div>
    {{ render_field(form.reviewers) }}
    <div class='field fields-flex'>
      <div>
        {% if form.pa.errors %}
        {{ form.pa(class='field-error') }}
        {% else %}
        {{ form.pa }}
        {% endif %}
        <label for='agreement' id='agreement'>
          I accept the <a href="{{ url_for('gen.publishing_agreement') }}" class='link' target='_blank'>publishing agreement</a>.
        </label>
      </div>
      <button type='submit' class='btn'>Submit</button>
    </div>
    <img src="{{ url_for('static', filename='gifs/spinner.gif') }}" width='24px' height='24px' class='spinner'>
  </form>
</main>
{% endblock content %}

acadome/articles/templates/search.html
{% extends '_base.html' %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<link rel='stylesheet' href="{{ url_for('articles.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('articles.static', filename='main.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='search-results hidden'>
  <form action="{{ url_for('articles.home') }}" method='GET' autocomplete='off' id='search-form'>
    <div class='fields-flex'>
      <input type='search' name='search' placeholder='Search database' value='{{ query }}'>
      <button type='submit' class='btn'>
        <img src="{{ url_for('static', filename='images/search.png') }}" width='16px' height='16px'>
      </button>
    </div>
  </form>

  <section class='search-grid'>
    {% for article in articles %}
    <div class='article hidden'>
      <p class='small'>
        {% if article['preprint'] %}
        <span>{{ article['accepted'].strftime('%d %b %Y') }} | </span>
        {% else %}
        <span>{{ article['published'].strftime('%d %b %Y') }} | </span>
        {% endif %}
        {% for author in article['authors'] %}
        {% if author == article['authors'][-1] %}
        <span><a href="{{ url_for('articles.author_search', author=author.replace(' ', '_')) }}" class='blue'>{{ author }}</a></span>
        {% else %}
        <span><a href="{{ url_for('articles.author_search', author=author.replace(' ', '_')) }}" class='blue'>{{ author }}</a>, </span>
        {% endif %}
        {% endfor %}
      </p>
      <p>
        {% if article['preprint'] %}
        <span class='preprint small'>Preprint</span>
        {% endif %}
        <a href="{{ url_for('articles.article', id=article['id']) }}" class='blue'>{{ article['title'] }}</a>
      </p>
    </div>
    {% endfor %}
  </section>

  <section class='no-results hidden'>
    <span>There are no results for your search query.</span>
  </section>

  <ul class='pagin hidden'>
    <li><a></a></li>
    <li></li>
    <li><a></a></li>
  </ul>
</main>
{% endblock content %}