acadome/editors/__init__.py
from flask import Blueprint

editors = Blueprint(
    'editors',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/editors/static',
    url_prefix='/editors'
)

from acadome.editors import views

acadome/editors/views.py
from flask import render_template, redirect, url_for, abort
from acadome import db, um
from acadome.editors import editors

def find_article(id):
    article = db.queue.find_one({'id': id})
    if not article:
        abort(404)
    return article

@editors.route('/')
@um.user_required
@um.redirect('admin', 'admin.home')
@um.access('editor')
def home():
    articles = db.queue.find().sort([('submitted', 1)])
    fields = db.fields.find().sort([('name', 1)])
    return render_template('editors_home.html', title='Editor', articles=articles, fields=fields, um=um)

@editors.route('/article/<string:id>')
@um.user_required
@um.access('editor')
def article(id):
    article = find_article(id)
    return render_template('editors_article.html', title=article['title'], article=article, um=um)

@editors.route('/article/<string:id>/accept')
@um.user_required
@um.access('editor')
def accept_article(id):
    article = find_article(id)
    db.queue.update_one({'id': id}, {
        '$push': {'votes.accept': um.user['name']}
    })
    return redirect(url_for('editors.article', id=id))

@editors.route('/article/<string:id>/reject')
@um.user_required
@um.access('editor')
def reject_article(id):
    article = find_article(id)
    db.queue.update_one({'id': id}, {
        '$push': {'votes.reject': um.user['name']}
    })
    return redirect(url_for('editors.article', id=id))

acadome/editors/templates/editors_article.html
{% extends '_base.html' %}

{% block content %}
<main class='grid31 hidden'>
  <article>
    <a href="{{ url_for('editors.home') }}" class='small orange'>&lt; Back</a>
    <h2>{{ article['title'] }}</h2>
    <p>{{ ', '.join(article['authors']) }}</p><br>
    <div>
      <a href="{{ url_for('articles.static', filename='pdfs/queue/' + article['id'] + '/preprint.pdf') }}" target='_blank' class='btn'>PDF</a>
    </div><br>
    <h3>Abstract</h3>
    <p>{{ article['abstract'] }}</p><br>
    <h3>Keywords</h3>
    <p>{{ ', '.join(article['keywords']) }}</p>
  </article>
  <aside>
    <p>
      Submitted on: {{ article['submitted'].strftime('%d %B %Y') }}<br>
      {% if article['preprint'] %}
      Accepted on: {{ article['accepted'].strftime('%d %B %Y') }}<br>
      {% endif %}
    </p><br>
    {% if um.user['name'] in article['votes']['accept'] %}
    <p>Voted for: <span class='green'>Accepted</span></p>
    {% elif um.user['name'] in article['votes']['reject'] %}
    <p>Voted for: <span class='red'>Rejected</span></p>
    {% else %}
    <p>
      Vote to:
      <a href="{{ url_for('editors.accept_article', id=article['id']) }}" class='btn green'>Accept</a>
      <a href="{{ url_for('editors.reject_article', id=article['id']) }}" class='btn red'>Reject</a>
    </p><br>
    {% endif %}
    {% if article['reviewers'] %}
    <h3>Reviewers</h3>
    {% endif %}
    <p>{{ ', '.join(article['reviewers']) }}</p>
    {% if article['editor'] %}
    <h3>Editor</h3>
    <p>{{ article['editor'] }}</p>
    {% endif %}
  </aside>
</main>
{% endblock content %}

acadome/editors/templates/editors_home.html
{% extends '_base.html' %}

{% block meta %}
<link rel='stylesheet' href="{{ url_for('forms.static', filename='style.css') }}" type='text/css'>
<link rel='stylesheet' href="{{ url_for('articles.static', filename='style.css') }}" type='text/css'>
<script defer src="{{ url_for('forms.static', filename='router.js') }}" type='text/javascript'></script>
{% endblock meta %}

{% block content %}
<main class='search-results hidden'>
  <form action="{{ url_for('editors.home') }}" method='GET' id='field-form'>
    <select name='field'>
      <option value='article'>All fields</option>
      {% for field in fields %}
      <option value="{{ field['name'] }}">{{ field['name'] }}</option>
      {% endfor %}
    </select>
  </form>

  <section class='search-grid'>
    {% for article in articles %}
    <div class="article {{ article['field'] }}">
      <p>
        {% if article['preprint'] %}
        <span class='small'>{{ article['accepted'].strftime('%d %b %Y') }} | </span>
        {% else %}
        <span class='small'>{{ article['submitted'].strftime('%d %b %Y') }} | </span>
        {% endif %}
        <span class='small'>{{ ', '.join(article['authors']) }}</span><br>
        <a href="{{ url_for('editors.article', id=article['id']) }}" class='blue'>{{ article['title'] }}</a>
      </p>
    </div>
    {% endfor %}
  </section>

  <section class='no-results hidden'>
    <span>There are no articles in the queue.</span>
  </section>
</main>
{% endblock content %}